title: Thiago Ângelo Gelaim
logo: /assets/img/logo.png
description: PhD in computer science at Federal University of Santa Catarina. Interested in Artificial Inteligence, Situational awareness, Natural Language Processing, Virtual Reality, Agents and Multi-agents.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
